### ISSUE TITLE
Fail build with Qt 5.11

### ISSUE THREAD

**Issue by sl1pkn07** [meganz/MEGAsync#186]
with Qt 5.11beta3

```
g++ -c -pipe -g -g -Wall -W -D_REENTRANT -fPIC -DQT_DISABLE_DEPRECATED_BEFORE=0x000000 -DCREATE_COMPATIBLE_MINIDUMPS -DLOG_TO_STDOUT -DLOG_TO_LOGGER -DSHOW_LOGS -DHAVE_LIBUV -DUSE_MEDIAINFO -DUSE_SQLITE -DUSE_CRYPTOPP -DUSE_QT -DMEGA_QT_LOGGING -DENABLE_SYNC -DENABLE_CHAT -DSQLITE_DEBUG -DDEBUG -DUSE_DBUS -DQT_NO_CAST_FROM_ASCII -DQT_NO_CAST_TO_ASCII -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I. -Igui -Igui/linux -I/tmp/makepkg/megasync-git/src/MEGAsync/src/MEGASync/mega/bindings/qt/../..//bindings/qt/3rdparty/include/libuv -Imega/include -Imega/bindings/qt -I/tmp/makepkg/megasync-git/src/MEGAsync/src/MEGASync/mega/bindings/qt/../..//bindings/qt/3rdparty/include -Imega/include/mega/posix -Icontrol -Iplatform -Igoogle_breakpad -Iqtlockedfile -I. -isystem /usr/include/qt -isystem /usr/include/qt/QtSvg -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtDBus -isystem /usr/include/qt/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/qt/mkspecs/linux-g++ -o AccountDetailsDialog.o gui/AccountDetailsDialog.cpp
gui/AccountDetailsDialog.cpp: In member function 'void AccountDetailsDialog::refresh(Preferences*)':
gui/AccountDetailsDialog.cpp:52:35: error: invalid use of incomplete type 'class QStyle'
         ui->pUsageStorage->style()->unpolish(ui->pUsageStorage);
                                   ^~
In file included from /usr/include/qt/QtWidgets/qdialog.h:44:0,
                 from /usr/include/qt/QtWidgets/QDialog:1,
                 from gui/AccountDetailsDialog.h:4,
                 from gui/AccountDetailsDialog.cpp:1:
/usr/include/qt/QtWidgets/qwidget.h:67:7: note: forward declaration of 'class QStyle'
 class QStyle;
       ^~~~~~
gui/AccountDetailsDialog.cpp:53:35: error: invalid use of incomplete type 'class QStyle'
         ui->pUsageStorage->style()->polish(ui->pUsageStorage);
                                   ^~
In file included from /usr/include/qt/QtWidgets/qdialog.h:44:0,
                 from /usr/include/qt/QtWidgets/QDialog:1,
                 from gui/AccountDetailsDialog.h:4,
                 from gui/AccountDetailsDialog.cpp:1:
/usr/include/qt/QtWidgets/qwidget.h:67:7: note: forward declaration of 'class QStyle'
 class QStyle;
       ^~~~~~
gui/AccountDetailsDialog.cpp:73:35: error: invalid use of incomplete type 'class QStyle'
         ui->pUsageStorage->style()->unpolish(ui->pUsageStorage);
                                   ^~
In file included from /usr/include/qt/QtWidgets/qdialog.h:44:0,
                 from /usr/include/qt/QtWidgets/QDialog:1,
                 from gui/AccountDetailsDialog.h:4,
                 from gui/AccountDetailsDialog.cpp:1:
/usr/include/qt/QtWidgets/qwidget.h:67:7: note: forward declaration of 'class QStyle'
 class QStyle;
       ^~~~~~
gui/AccountDetailsDialog.cpp:74:35: error: invalid use of incomplete type 'class QStyle'
         ui->pUsageStorage->style()->polish(ui->pUsageStorage);
                                   ^~
In file included from /usr/include/qt/QtWidgets/qdialog.h:44:0,
                 from /usr/include/qt/QtWidgets/QDialog:1,
                 from gui/AccountDetailsDialog.h:4,
                 from gui/AccountDetailsDialog.cpp:1:
/usr/include/qt/QtWidgets/qwidget.h:67:7: note: forward declaration of 'class QStyle'
 class QStyle;
       ^~~~~~
make: *** [Makefile:3383: AccountDetailsDialog.o] Error 1
```

**Comment by prototype99** [comment]
the same problem still occurs with 5.11.1

**Comment by sl1pkn07** [comment]
fixed in newer version of Qt/MEGASync

closed
