### ISSUE TITLE
Failure to build with GCC 9.2

### ISSUE THREAD

**Issue by Lillievela** [meganz/MEGAsync#366]
After having to reinstall Megasync it fails to build on Manjaro with GCC 9.2

**Comment by Frosch** [comment]
This is the error during build: 

```google_breakpad/client/linux/handler/exception_handler.cc: At global scope:
google_breakpad/client/linux/handler/exception_handler.cc:107:12: error: ‘int tgkill(pid_t, pid_t, int)’ was declared ‘extern’ and later ‘static’ [-fpermissive]
  107 | static int tgkill(pid_t tgid, pid_t tid, int sig) {
      |            ^~~~~~
In file included from /usr/include/signal.h:374,
                 from google_breakpad/client/linux/handler/exception_handler.h:37,
                 from google_breakpad/client/linux/handler/exception_handler.cc:66:
/usr/include/bits/signal_ext.h:29:12: note: previous declaration of ‘int tgkill(__pid_t, __pid_t, int)’
   29 | extern int tgkill (__pid_t __tgid, __pid_t __tid, int __signal);
      |            ^~~~~~
```

I'm also trying to build trying to build from AUR on Manjaro using gcc 9.2

**Comment by ix5231** [comment]
Workaround: Add `-fpermissive` to `QMAKE_CXXFLAGS`

For the AUR `PKGBUILD`:
```diff
diff --git a/PKGBUILD b/PKGBUILD
index 38d9165..0947609 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -55,7 +55,7 @@ build() {
 
     # build megasync
     cd "../.."
-    qmake-qt5 "CONFIG += FULLREQUIREMENTS" MEGA.pro
+    qmake-qt5 "CONFIG += FULLREQUIREMENTS" "QMAKE_CXXFLAGS += -fpermissive" MEGA.pro
     lrelease-qt5 MEGASync/MEGASync.pro
     make
 }
```

**Comment by Lillievela** [comment]
I have noticed that the AUR package is not really needed, I have managed to download the package from the actual site and install it perfectly fine. It seems to be that 4.2.5-2 is completely broken as 4.2.5-1 from the site works fine. I believe that the issue may be caused in the build files relating to how it is built. If the workaround works

**Comment by thefloweringash** [comment]
The problem is a definition of `tgkill` in breakpad conflicting with `tgkill` introduced in glibc 2.30. This has been [fixed upstream][], though with slightly different motivation.

[fixed upstream]: https://chromium.googlesource.com/breakpad/breakpad/+/7e3c165000d44fa153a3270870ed500bc8bbb461%5E%21/#F0

**Comment by thefloweringash** [comment]
See also #313
